services:
  - type: web
    name: django-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn student_management_system.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: student_management_system.settings
      - key: SECRET_KEY
        generateValue: true
